export const STRINGS = {
    change_leverage: 'Change Leverage',
    previous_leverage: 'Previous Leverage',
    new_leverage: 'Select New Leverage',
    loyality_program: 'Loyality Program',
    trading_accounts: 'Trading Accounts',
    position: 'Positions',
    watch_list: 'Watchlist',
    live_accounts: 'Live Accounts',
    hi: 'Hi ',
    how_can_we_help_you: "How can we help you?",
    demo_accounts: 'Demo Accounts',
    dear: 'Dear',
    submit: 'Submit',
    tools: 'Tools',
    historical_data: 'Historical Data',
    news: 'News',
    overview: 'Overview',
    news_details: 'News Details',
    notifications: 'Notifications',
    economic_calender: 'Economic calender',
    login: 'Login',
    work_progress: 'Work in Progress',
    register: 'Register',
    p_close: 'Partial Close',
    place_order: 'Place Order',
    market_insight: 'Market Insight',
    support: 'Support',
    sell: 'SELL',
    buy: 'BUY',
    sell_small: 'Sell',
    buy_small: 'Buy',
    free_margin: 'Free Margins',
    go_to_plan: 'Go to Plans',
    email_sent_msg_1: 'We have sent a link to your email',
    email_sent_msg_2: '. Please click on the link to change your leverage.',
    email_sent_msg_3: '. Please click on the link to change your Account Password.',
    sent_again: 'Have not received an email In your inbox or spam folder?',
    resend: 'Resend',
    back_to_accounts: 'Back to Accounts',
    points: 'Points',
    bronze: 'Bronze',
    send_otp: 'Send OTP',
    confirm_otp: 'Confirm OTP',
    silver: 'Silver',
    gold: 'Gold',
    diamond: 'Diamond',
    redeem: 'Redeem Now',
    select_account_type: 'Select Account Type',
    change_password: 'Change Password',
    account_id: 'Account ID',
    password: 'Password',
    enter_password: 'Enter your password',
    enter_confirm_password: 'Enter Confirm password',
    confirm_password: 'Confirm Password',
    confirm: 'Confirm',
    repeat_password: 'Repeat Password',
    create_account: 'Create Account',
    redeem_msg_1: 'Redeem your loyality Point',
    redeem_msg_2: 'We love to reward you as you grow with us',
    add_new_live_account: 'Add New Live Account',
    add_new_demo_account: 'Add New Demo Account',
    add_account: 'Add Account',
    X: 'X',
    USD: 'USD',
    GBP: 'GBP',
    CAD: 'CAD',
    AUD: 'AUD',
    ZAR: 'ZAR',
    EURO: 'EUR',
    INR: 'INR',
    CHF: "CHF",
    NZD: "NZD",
    NOK: "NOK",
    JPY: "JPY",
    TRY: "TRY",
    SGD: "SGD",
    SEK: "SEK",
    PLN: "PLN",
    CZK: "CZK",
    DKK: "DKK",
    HKD: "HKD",
    CNH: "CNH",
    MXN: "MXN",
    HUF: "HUF",
    RUB: "RUB",
    RON: "RON",
    ILS: "ILS",
    platform: 'Platform',
    currency: 'Currency',
    leverage: 'Leverage',
    congratulations: 'Congratulations',
    trading_id: 'Trading ID',
    account_create_success_msg_1: 'Your',
    account_create_success_msg_2: 'account has been successfully created. Your credentials are:',
    wallets: 'Wallets',
    add_new_wallet: 'Add New Wallet',
    available_amount: 'Available Amount',
    add_wallet: 'Add wallet',
    profile: 'Profile',
    set_alert: 'Set Alert',
    create_alert: 'Create Alert on',
    empty_password: 'Password must not be empty',
    wrong_password: 'Passwords must have at least 8 characters and contain at least two of the following: uppercase letters, lowercase letters, numbers, and symbols.',
    empty_confirm_password: 'Confirm Password must not be empty',
    wrong_confirm_password: 'Confirm Passsword must be same as of Password',
    select_country: 'Select your country',
    select_resedence_country: 'Select residence country',
    register_now: 'Register Now',
    enter_email_username: 'Enter your username or email ID',
    search_country: 'Search your country',
    forgot_password: 'Forgot Password?',
    login_credentials: 'Login with your credentials',
    username_email: 'Username or Email ID',
    forgot_password_msg: 'Don’t worry. Just enter your registered email address or your username(if remember), and we will get you back on track in minute.',
    empty_email: 'Email must not be empty',
    valid_email: 'Must be valid email',
    email_id: 'Email ID',
    otp_send_msg: 'We will share an OTP on your registered email ID.',
    reset_password: 'Reset Password?',
    password_msg: 'Your password must contain at least 6 characters, and include at least 1 number, 1 uppercase character and 1 special character (!@#$%^&*)',
    password_link_msg_1: 'A link for change password has been sent on your registered email id',
    password_link_msg_2: 'Now please go back to login screen by clicking on the below button and login to your account.',
    back_to_login: 'Back to Login',
    quickly_continue: 'Quickly Continue with',
    google: 'Continue with Google',
    apple: 'Continue with Apple',
    finvasia: 'Continue with Finvasia ID',
    email: 'Continue with Email ID',
    quickly_registered: 'Quickly Register with',
    about: 'About Me',
    fname: 'First Name',
    star: '*',
    lname: 'Last Name',
    dob: 'Date of Birth',
    next: 'Next',
    e_lastname: 'Enter your last name',
    e_fastname: 'Enter your first name',
    postal_code: 'Postal Code',
    e_postal_code: 'Postal Code of your area',
    r_address_1: 'Residential Address Line 1',
    e_address_line_1: 'Address line 1',
    r_address_2: 'Residential Address Line 2',
    e_address_line_2: 'Address line 2',
    e_city: 'Enter your City',
    city: 'City',
    address: 'Address',
    country: 'Country',
    additional_details: 'Additional Details',
    phone_number: 'Phone Number',
    e_phone_number: 'Enter Mobile number',
    wallet_currency: 'Wallet Currency',
    e_wallet_currency: 'Select the wallet currency type',
    pep: 'Are you a Politically exposed Person(PEP)?',
    appropriate_answer: 'Select appropriate answer',
    us_person: 'Are you a US person?',
    min_age_error_msg: 'Minimum required age is 18 to start trading',
    financial_details: 'Financial Details',
    occupation_title: 'If Employed please specify',
    occupation_placeholder: 'Select Occupation',
    income_title: 'Estimated Annual Income (USD)',
    income_placeholder: 'Select annual Income',
    networth_title: 'Estimated Net Worth (USD)',
    networth_placeholder: 'Select net worth',
    fund_title: 'Source of Funds ',
    agree_continue: 'Agree & Continue',
    fund_placeholder: 'Select Source of funds',
    declaration: 'Declaration',
    checkbox_1_1: 'I have read, understood and accept the ',
    checkbox_1_2: 'Client Agreement',
    checkbox_1_3: 'Privacy Policy',
    checkbox_1_4: ' and ',
    checkbox_1_5: 'Risk Disclosure documents ',
    note: 'Note: After clicking on "Save & Continue", you will not be able to change any previous step information. Make sure all information is correct!',
    checkbox_2: 'I agree for my personal data to be processed and stored as per the Privacy Policy, and for Fxview to contact me regarding important information for my account',
    email_sent: 'Email sent',
    select_leverage: 'Please select new leverage',
    my_account: 'My Account',
    more: 'More',

    personal_details: 'Personal details',
    bank_details: 'Bank Details',
    documents: 'Documents',
    charts: 'Mini Charts',
    chart: 'Chart',
    info: 'Info',
    pivot_points: 'Pivot Points',
    terminal: 'Mini Terminal',
    trader_toolbox: "Trader's Tool box",
    subscription: 'Subscription',
    vps: 'VPS',
    vps_full: 'Virtual Private Server',
    standard_package: 'STANDARD PACKAGE',
    basic_package: 'BASIC PACKAGE',
    premium_package: 'PREMIUM PACKAGE',
    per_month: '/Month',
    select_another_plan: 'Select Another Plan',
    cancel_subscription: 'Cancel Subscription',
    cancel: 'Cancel',
    choose_plan: 'Choose this Plan',
    warning_message: 'Are you sure your want to subscribe to ',
    plan_changed: 'Plan changed Successfully',
    internal_transfer: 'Internal Transfer',
    another_trading_account: 'Select another trading account',
    search_account: 'Search account',
    select_account: 'Select Account',
    enter_amount: 'Enter Amount',
    deposite_amount: 'Enter the amount you want to deposite',
    transfer: 'Transfer',
    edit: 'Edit',
    total_balance: 'Total Balance',
    transfer: 'Transfer',
    withdraw: 'Withdraw',
    internal_transfer_msg: '.Please click on the link to confirm your internal transfer',
    internet_issue: 'Internet not connected',
    internal_server: 'Server error 500',
    bad_request: 'BAD request 400',
    session_expire: 'Session logged out',
    select_platform: 'Please select Platform',
    select_currency: 'Please select Currency',
    select_platform: 'Please select Platform',
    server_issue: 'Server issue',
    enter_first_name: 'Please enter your First Name',
    enter_last_name: 'Please enter your Last Name',
    select_dob: 'Please select your date of birth',
    enter_mobile: 'Please enter your mobile number',
    select_pep: 'Please Tell us Are you a US Person',
    enter_city: 'Please enter your city',
    enter_address: 'Please enter address',
    enter_postal_code: 'Please enter postal code',
    accept_terms: 'Please accept Terms & Conditions',
    select_occupation: 'Please select occupation',
    select_estimated_income: 'Please select Estimated Income',
    select_net_worth: 'Please select Net Worth',
    fund_source: 'Please select Fund Source',
    deposite: 'Deposite',
    withdraw: 'Withdraw',
    converter_line_1: ' will be deducted from your trading account ',
    converter_line_2: ' will be deposited to your wallet ',
    confirm_continue: 'Please confirm to continue',
    and: 'and',
    symbol: 'Symbol',
    qty: 'QTY',
    ltp: 'LTP',
    investment: 'Investment',
    market_value: 'Market Value',
    gain_loss: 'Gain/Loss (%)',
    see_all: 'See All',
    top_positions: 'Top Positions',
    top_traders: 'Top Traders',
    portfolio_value: 'Portfolio value',
    used_margin: 'Used Margin ',
    pl: 'P/L ',
    account_not_added: 'You have not added any account yet',
    previous: 'Previous: ',
    forecast: 'Forecast: ',
    actual: 'Actual: ',
    search_topic: "Search Topic",
    search_any_topic_you_need_help_with: "Search any topic you need help with",
    or_select_a_topic_from_below: "Or Select a topic from below",
    generate_ticket: 'Generate Ticket',
    get_help_with: "Get Help With {text} in Profile Support",
    subject: "Subject",
    your_message: "Your Message",
    upload_documents: "Upload Documents",
    remove: 'Remove',
    existing_email_address: "Existing email address",
    new_email_address: "New email address",
    change_email_address: "Change Email Address",
    change_phone_number: "Change Phone Number",
    submit_phone_number: "Submit Phone Number",
    add_new_phone_number: 'Add New Phone Number',
    existing_phone_number: "Existing phone number",
    new_phone_number: "New phone number",
    country_code: "Country Code",
    change_address: "Change Address",
    i_am_not_satisfied: "I'm not satisfied",
    instrument: 'Instrument',
    instrument_list: 'Instrument List',
    open_rate: 'Open Rate',
    current_rate: 'Current Rate',
    trading_stop_order: 'Tr. Stop Order',
    date_time: 'Date/Time',
    amount: 'Amount',
    charges: 'Charges',
    stop_order: 'Stop Order',
    limit_order: 'Limit Order',
    close: 'Close',
    modify_order: 'Modify',
    open: "Open",
    islamic_note: `Note: In order to convert your account to Islamic, Please make sure first you close all open positions in all your trading accounts. Once your account gets converted, you will not be able to access any of your ECN trading accounts. Also, Islamic account is available on MT4 trading platform only, in case you have any balance in MT5 or ActTrader, it will be automatically transferred to your wallet.`,
    request_islamic_account: "Request Islamic account",
    islamic_checkbox_content: "I do not have any open positions in my trading accounts",
    ok: "OK",
    high: 'High',
    low: 'Low',
    add_to_watch_list: 'Add to Watchlist',
    msg: 'Message Type here',
    open: "Open",
    close: "Close",
    islamic_note: `Note: In order to convert your account to Islamic, Please make sure first you close all open positions in all your trading accounts. Once your account gets converted, you will not be able to access any of your ECN trading accounts. Also, Islamic account is available on MT4 trading platform only, in case you have any balance in MT5 or ActTrader, it will be automatically transferred to your wallet.`,
    request_islamic_account: "Request Islamic account",
    islamic_checkbox_content: "I do not have any open positions in my trading accounts",
    ok: "OK",
    contact_form: "Contact Form",
    full_real_name: 'Full Real Name',
    prefered_contact_time: 'Prefered Contact Time (GMT)',
    question_or_comments: "Question Or Comments",
    select_time_zone: "Select Time Zone",
    market: 'Market',
    sell_stop: 'Sell Stop',
    sell_limit: 'Sell Limit',
    buy_stop: 'Buy Stop',
    buy_limit: 'Buy Limit',
    comment: 'Comment',
    traling_stop_loss: 'Traling Stop Loss',
    traling_stop: 'Traling Stop',
    target_price: 'Target price',
    market_range: 'Market range',
    quantity: 'Quantity',
    price_level: 'Price Level',
    rate: 'Rate',
    stop_loss: 'Stop Loss',
    advance_options: 'Advance options',
    price: 'Price',
    search_symbol: 'Search Symbols',
    calculator: "Calculator",
    commission: "Commission",
    margin: "Margin",
    multi_target: "Multi-Target",
    fibonacci: "Fibonacci",
    pip_value: "Pip Value",
    swap: "Swap",
    position_size: "Position Size",
    currency_convertor: "Currency Convertor",
    profit_loss: "Profit & Loss",
    assets_class: "Assets Class",
    select_assets_class: "Select Assets Class",
    forex: "Forex",
    commodities: "Commodities",
    indices: "Indices",
    stocks: "Stocks",
    cryptos: "Cryptos",
    account_base_currency: "Account Base Currency",
    select_account_base_currency: "Select Account Base Currency",
    currencies: "currencies",
    xauusd: "XAUUSD",
    indicies: "INDICIES",
    crypto: "crypto",
    select_symbol: "Select Symbol",
    trade_size_in_lots: "Trade Size (in lots)",
    account_leverage: "Account Leverage",
    position_type: "Position Type",
    open_price: "Open Price",
    stop_loss_price: "Stop Loss Price",
    target_price1: "Target Price 1",
    target_price2: "Target Price 2",
    target_price3: "Target Price 3",
    lots_closed_at_target1: "Lots Closed At Target 1",
    lots_closed_at_target2: "Lots Closed At Target 2",
    lots_closed_at_target3: "Lots Closed At Target 3",
    uptrend: "Uptrend",
    downtrend: "Downtrend",
    number_of_days: "Number Of Days",
    stop_price: "Stop Price",
    account_balance: "Account Balance",
    risk_percentage: "Risk Percentage",
    currency_from: "Currency From",
    currency_to: "Currency To",
    mt4: 'MT4',
    mt5: 'MT5',
    mt4_link: 'https://play.google.com/store/apps/details?id=net.metaquotes.metatrader4&hl=en&gl=US',
    mt5_link: 'https://play.google.com/store/apps/details?id=net.metaquotes.metatrader5&hl=en&gl=US',
    calculate_now :"Calculate Now",
    converted_currency:"Converted Currency:",
    otp_sent_msg_2:'We will share an OTP on your registered Mobile Number.',
    enter_otp:'Enter OTP',
    enter_otp_msg_1:'Enter the Verification code we have sent on',
    select_account_msg:'Please select Account',
    verified: 'Verified',
    non_verified:'Non - Verified',
    failed:'Failed',
    name:'Name',
    email_label:'Email',
    address:'Address',
    dob:'DOB',
    mobile:'Mobile',
    bank_name:'Bank Name',
    account_number:'Account Number',






}
export const labels = ["Bronze", "Silver", "Gold", "Diamond"];
export const currency_signs = {
    USD: '$',
    EUR: '€',
    AUD: '$',
    GBP: '£',
    CAD: '$',
    ZAR: 'R',
};
export const features = [
    'Month-to-Month subscription',
    '2 GB Memory / 2 VCPU',
    '50 GB SSD Disk Space',
    '2 TB Traffic',
    'MT4 / MT5 / ActTrader',
    'Managed VPS Service Option',
    'Window 2019x64STD'
];


